[[ducc0]]
arch = "aarch64"
git-tree-sha1 = "fee2210b7cdb972cca995cae6e221726c3457b76"
lazy = true
os = "macos"

    [[ducc0.download]]
    sha256 = "8372321ffae01fce8b9ef2bc64800415f27bfc18b75c30381d3ef606c6aebe91"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.aarch64-apple-darwin.tar.gz"
[[ducc0]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75e2a418782771350852da1fdc6365aba8495308"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "85b08599e6b5304558f662f925b29a4d3b551b6208cd2d09eea68a638005bd63"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ducc0]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a05d1e1e786e4a5376d4e0be01a09b5325c34e2"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "e731d518f96685e1d75dfb74aa36b630d3b2a4d142ff3d810f2d0a9f77fae5ff"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ducc0]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a54331bc8144a488dbc0f5f84c65fe0a8889f860"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "a2daa96ac0fb3231226bb9420fc245f4d198003105ce553a562d9a6814b0e0f1"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.aarch64-linux-musl-cxx03.tar.gz"
[[ducc0]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc378e4e0dc4ce68d6b350451c86d461ab6852a4"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "36aca1153b0d07fee5819b0cdd4937dfac773f8ca41412a9f9f61003a64a06f4"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.aarch64-linux-musl-cxx11.tar.gz"
[[ducc0]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7564ea95f72c218dc1cd782ce8419df8752092e6"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "7527a9d521259a1c07fbfe37211df3923bb3f22aa4379d05c09a7f8d4e81e0c5"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ducc0]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "613a07f17aa21f654dee4d29a29784020f801eaf"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "29a68cc5f53757d7c32a5b3367223633f0b140f31be7003bb78c4a58d0894493"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ducc0]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c81cda360fed601fb457c9b6ff889c7af7387a5"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "310ff1b9935381038a8853bcc50d185486815c43002502d13ed8218fde920107"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ducc0]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "495ef7702926476fcb7de78211eae30ce7c37df2"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "f2d53a8f1ce8262ffac23e5e62bca4156bc6cd087384981ad753b073ca496f7b"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ducc0]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03b5ea5626b5557c92cc7ca86e9154141963bc58"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "25742af8290b942d5d72f73734304a28264d6c66a534a065e99e9e79a1c3900b"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ducc0]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b014d7f363edf6f5dbbb4c5be7b5e5116ba44320"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "8862fc5be6823b46eedb9dadf13f246a0b968498892f3fed1d2464baef426e09"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ducc0]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef628219511afa1ee6e615ba9e7d2e9b76c2f2e6"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "ea0dbe95db0f4c8ab1a85e075f8a047da28eda904d92a056ec033b559ffab57f"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ducc0]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e373e5d0b34eed7a9169c503fcb8821b4b75377b"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "46f711318589a97ce39ac635eeef5db64cab3693d650281692804eab0f3314d8"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ducc0]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9a6e4ef4addbb4b9f4d040ea1e2f83bac94e073"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "dbd307ab3e3089b5755be62af7dba251ffb93cff18b1e96ed2690ebf6d0fb7c6"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.i686-linux-gnu-cxx03.tar.gz"
[[ducc0]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88141f216e1e07a7787196babe853a1f9f1bda2e"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "ce9ea51d86a72852743d2e5792521bf360ea04af55a92254f198f26b3ea6d954"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.i686-linux-gnu-cxx11.tar.gz"
[[ducc0]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85c223b059ef2392332f8651118ddd17f6382443"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "a37a5774e7e833ae8376462d52601d88aa41ca27dfcff618282cc459ca5fe848"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.i686-linux-musl-cxx03.tar.gz"
[[ducc0]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff2b4858335c2875776196d29346aa44c2934c82"
lazy = true
libc = "musl"
os = "linux"

    [[ducc0.download]]
    sha256 = "0681234c5146b8cae99f26f3f1267e30501dc3b27b7849d8248587ffdd8528a2"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.i686-linux-musl-cxx11.tar.gz"
[[ducc0]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c5a9929320ead57bed7e6f14bd88a1eea5e22ee"
lazy = true
os = "windows"

    [[ducc0.download]]
    sha256 = "1919da9c0d41e3fc18361beaed22ea4eddd9350c7bb3258754001565a3ecf6b8"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.i686-w64-mingw32-cxx03.tar.gz"
[[ducc0]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94c1516743fea4b989cac1d758b2438e84e04952"
lazy = true
os = "windows"

    [[ducc0.download]]
    sha256 = "403286cc31b4738d4c7132ceb13ad11fc9109c962a9e0749a3e0af0e5c010b57"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.i686-w64-mingw32-cxx11.tar.gz"
[[ducc0]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d41f7c2c8b7dd56e6926253ddf212dab6fe36dc"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "fd09217333de29f1c63089a8baa1afdc26d8e20117f96c1189badee47c748996"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ducc0]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6242b1968593710da895777153228580d5eb3954"
lazy = true
libc = "glibc"
os = "linux"

    [[ducc0.download]]
    sha256 = "d2888653c2e5a55655f3e0ec5d83e84c52181eebe1f028fb8fe0278edff2eb00"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ducc0]]
arch = "x86_64"
git-tree-sha1 = "063ceb7847376b72af5c3af28b277be5648170de"
lazy = true
march = "avx"
os = "macos"

    [[ducc0.download]]
    sha256 = "fbd07c99399b918cad691088b00836b5368cb944dba28bb7d0bda118106f9979"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-apple-darwin-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
git-tree-sha1 = "d1b838a857b662fc386d7bdd29640f30907049f8"
lazy = true
march = "avx2"
os = "macos"

    [[ducc0.download]]
    sha256 = "f7c4ec67f077bf20ecfc6edfa8a9a39f1ddd9e64e13e90212c50bae1cd7cd947"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-apple-darwin-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
git-tree-sha1 = "db31aa742d219a07b612cceca4373668223c34bd"
lazy = true
march = "x86_64"
os = "macos"

    [[ducc0.download]]
    sha256 = "eb9b0999069030e4a1aa509506a7e00ec04b6003d76c1266bf70cb5e7f128986"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-apple-darwin-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "506ddd726a54074e401e5e0fc3888b5348e134bf"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[ducc0.download]]
    sha256 = "cc032614c5943190e3260c84c34ba38466076c3914cbf104611a6f4fbe0e5e7a"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-gnu-cxx03-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59d0032194081f4c3cf5e77fb604f9a2016ea6e9"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[ducc0.download]]
    sha256 = "5bbc5562342ce0698489d66834a38990b8d1c84c0c7848eab7072910f5000c88"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-gnu-cxx03-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bdfdb112abc1965613fbe67199a6dc343cb3bde"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[ducc0.download]]
    sha256 = "34162dac098fc04dc32682777085a61e9026c25404958c7a4d4c6b9e2c143fc9"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-gnu-cxx03-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cf566327d56183cc8cec3426901b934ff622698"
lazy = true
libc = "glibc"
march = "avx"
os = "linux"

    [[ducc0.download]]
    sha256 = "7db425d93b0611bb124fe48561f0db083d4b993b4d6e662eab7c1bcf923da0b4"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-gnu-cxx11-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b14b2d972cba8bc6e9701d9b7ff7c5bec5109129"
lazy = true
libc = "glibc"
march = "avx2"
os = "linux"

    [[ducc0.download]]
    sha256 = "250b7b48d3bd2a14880f57164410988782dc6ea19c8e29f6790dffb1444c47a4"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-gnu-cxx11-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e013316330adf43a2f5411963ef09b37eb02cb41"
lazy = true
libc = "glibc"
march = "x86_64"
os = "linux"

    [[ducc0.download]]
    sha256 = "8f4a481f0f4930ff768939d2de83814cce231edaa4af809ab82a3c8559e97598"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-gnu-cxx11-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33867a1005313ab1f80fea8a28c35da9544bc665"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[ducc0.download]]
    sha256 = "a8721433279eb649125766d2e2c6a005375bcf722250021c45ec115f35a8d8ea"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-musl-cxx03-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02f4b5a5628f34e091058f79a33e5f4abd7c7a85"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[ducc0.download]]
    sha256 = "e04d07bdfcae45324faf50f537447728c95e483e933dc109748ce5d2defc7e16"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-musl-cxx03-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1a280b48418feb50271c13435af64f65448d824"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[ducc0.download]]
    sha256 = "becc170c9322c0b197e74b74badea77e8a7f32bfa5d7bc78c3b44546e45211d7"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-musl-cxx03-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09c86c4fb2f47f28e9d7aba1aedef38850944d40"
lazy = true
libc = "musl"
march = "avx"
os = "linux"

    [[ducc0.download]]
    sha256 = "3d3309a9a9bba051b26c82abbf0f334e37c612fee418031469d8c1760005f216"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-musl-cxx11-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74546b0750079afa209f764cc7c3c014d133d4c4"
lazy = true
libc = "musl"
march = "avx2"
os = "linux"

    [[ducc0.download]]
    sha256 = "e08dfcb92a0fb58366ecc0962b73590de2e91e0c090b0f756552e0817e41722b"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-musl-cxx11-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1868f802bb8aba6c1e57a232a82126beacbff277"
lazy = true
libc = "musl"
march = "x86_64"
os = "linux"

    [[ducc0.download]]
    sha256 = "a28853fcc1b879adacd1aa3595dccfe759071fcfa8eccaf62ec3ec69af6c3d09"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-linux-musl-cxx11-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
git-tree-sha1 = "ec90b0cf145afa0d4ef7bacf1d41161c1da7f2e3"
lazy = true
march = "avx"
os = "freebsd"

    [[ducc0.download]]
    sha256 = "141792ad1ac51999d55795bee293c4bf9851eaf47756c56e2a0c78fe770752ff"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-unknown-freebsd-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
git-tree-sha1 = "2dd6e8b17fa7f1fe1789f2bd7a412108d59b47e9"
lazy = true
march = "avx2"
os = "freebsd"

    [[ducc0.download]]
    sha256 = "788d17b855c88c34280723756bf72f2bddb68dc256ff7224544381c0ba0020be"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-unknown-freebsd-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
git-tree-sha1 = "c92b42ca219c95c36772c1b6262a892bb039cdd1"
lazy = true
march = "x86_64"
os = "freebsd"

    [[ducc0.download]]
    sha256 = "14a3956660cda91a88713b21858d36e918eed8f31eb3caff5b1217808369c210"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-unknown-freebsd-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0ba12f58038a3b87c6d1be90ed6483c41db9f4a"
lazy = true
march = "avx"
os = "windows"

    [[ducc0.download]]
    sha256 = "8ddb63d65111357b62111867c6a57d41f867d83365d8adbf5c09dd91d064e48c"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-w64-mingw32-cxx03-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0a8c0eeaf26758772c6f37a437881e1f4c6412c"
lazy = true
march = "avx2"
os = "windows"

    [[ducc0.download]]
    sha256 = "cf2caf3eca4fa14addaff79385ad609aedd54e6368c5200400a89b3108b1f7d3"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-w64-mingw32-cxx03-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67f6b01aed6f9b4f1031ac2a605984b664bef49c"
lazy = true
march = "x86_64"
os = "windows"

    [[ducc0.download]]
    sha256 = "ed8f24fd146c455de8b9b23c9123119975db2da1f2267a531622af998930dd79"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-w64-mingw32-cxx03-march+x86_64.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23fa4020e4114483e4b1976971fea97290f5f73f"
lazy = true
march = "avx"
os = "windows"

    [[ducc0.download]]
    sha256 = "630297cea201c04655cfa9c4f6f3042aec17c8a75c28144f6da60e838fcfa41c"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-w64-mingw32-cxx11-march+avx.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d75fb2c063f26fbdf324fdb0cb3b5b07865e1055"
lazy = true
march = "avx2"
os = "windows"

    [[ducc0.download]]
    sha256 = "a3491bbe24267523ac26f613ec790ea69f90b8e66fcf1daf6c63475ba7fa8e86"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-w64-mingw32-cxx11-march+avx2.tar.gz"
[[ducc0]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e28191707b65f7e5d13b908b6fc77d5ea1a6feba"
lazy = true
march = "x86_64"
os = "windows"

    [[ducc0.download]]
    sha256 = "9dded73bf1a3d17c23752d3ebb5e710189ab0fe0e909862aede6e01738abdc9a"
    url = "https://github.com/JuliaBinaryWrappers/ducc0_jll.jl/releases/download/ducc0-v0.28.0+0/ducc0.v0.28.0.x86_64-w64-mingw32-cxx11-march+x86_64.tar.gz"
